### ISSUE TITLE
Feature Request: Add a field for commit message 

### ISSUE THREAD

**Issue by derekwsgray** [lukasoppermann/design-tokens#224] opened 2022-08-18 20:14 UTC
When pushing to GitHub from the plugin, we need a way to specify what changed so that when a new version of the tokens are published we can have a change log (e.g. using https://github.com/semantic-release/semantic-release). With that we can use semantic-versioning conventions to know if the release is a breaking change or not (e.g. a token is removed, thus breaking, or just updated or added.)

**Comment by derekwsgray** [comment] 2022-08-18 21:25
I'll create a PR. But I have no clue how to run/test it in Figma :)

**Comment by lukasoppermann** [comment] 2022-08-23 11:55
This is actually a duplicate of #169

**Comment by lukasoppermann** [comment] 2022-08-29 08:14
fixed by #227 thanks again @derekwsgray 🙌

**Closed by lukasoppermann** 2022-08-29 08:14 UTC
