### ISSUE TITLE
Empty export, previously worked.

### ISSUE THREAD

**Issue by davidbwaters** [lukasoppermann/design-tokens#70] opened 2021-03-11 22:30 UTC
I'm getting an empty file trying to export.  Was working before.  Here's the view link https://www.figma.com/file/35nU0g9gYNgOwhp6cqTEIs/style-guide?node-id=0%3A1

**Comment by lukasoppermann** [comment] 2021-03-12 07:29
Hey @davidbwaters,

I can't access the file (I guess due to missing permissions).

**Comment by davidbwaters** [comment] 2021-03-12 15:20
sorry, updatesd

**Comment by lukasoppermann** [comment] 2021-03-12 15:28
Hey, so what do you expect to be exported? Does it export the text and color styles they not exported? If not, did you change anything in the settings? (Can you send a screenshot of your plugin settings)?

Lastly, can you check the console? In figma you can open the console via: `[Main Menu] > Plugins > (More) > Development > Open Console` 

Does it provide an error message?

**Comment by davidbwaters** [comment] 2021-03-13 20:02
I'm getting a file with an empty array both locally saving and when trying to push to repo.  Only console error showing is `URL is not defined` when saving locally, but when I empty the publish url in settings and try to save locally there are no errors and it still fails.  I have maybe 50 styles total. Image fills, colors, fonts, shadows.  I tried removing selections to pinpoint problem and export still failed.  The styles are in a published library/design system, but i imported the library in a new file and detached a few styles to be local and still got a failure.  The styles are in folders.  I made the link public read only. I'm not sure if you can reproduce by copying as a draft and exporting.  If you want to give me your email I can give you write access.
<img width="553" alt="CleanShot 2021-03-13 at 14 48 23@2x" src="https://user-images.githubusercontent.com/5247627/111042796-1f546d00-840d-11eb-8f73-a18034fe76a8.png">
<img width="231" alt="CleanShot 2021-03-13 at 14 52 03@2x" src="https://user-images.githubusercontent.com/5247627/111042797-20859a00-840d-11eb-84f4-c24de4ad7208.png">
<img width="554" alt="CleanShot 2021-03-13 at 14 50 42@2x" src="https://user-images.githubusercontent.com/5247627/111042798-20859a00-840d-11eb-8f22-ae42d6472314.png">

**Comment by lukasoppermann** [comment] 2021-03-14 07:02
Hey looks good.

If you can grant me write access that would be very helpful: oppermann.lukas@gmail.com

**Comment by davidbwaters** [comment] 2021-03-18 20:04
Thanks a lot.  Okay, I'll add you.

**Comment by lukasoppermann** [comment] 2021-03-18 20:31
Hey @davidbwaters,

it appears the issue is, that you set the "exclude" setting to only "include" the prefixed items. If you change it the import works fine.

This option definitely needs some reworking in at least the wording and description, as it is currently easy to misunderstand.

Sorry for the inconvenience.  Let me know if activating the prefix exclude option works for you.

**Comment by lukasoppermann** [comment] 2021-03-26 12:27
Hey, I am closing this as fixed now, if your issues still persist, please let me know.

**Closed by lukasoppermann** 2021-03-26 12:27 UTC

**Comment by davidbwaters** [comment] 2021-03-28 22:44
Thanks a lot man.  I think this is working.  I left some feedback (responding to when you asked how it could potentially be improved UX-wise) in the other closed issue, btw.  Thanks a lot.
